version: '3'

services:
  prod:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

    volumes:
      - type: bind
        source: ..
        target: /home/jovyan/work

    command: 
      - jupyter
      - lab
      - --allow-root
      - --ip='0.0.0.0'
      - --ServerApp.allow_origin='*'
    ports:
      - 8888:8888
#  dev:
#
#    build: 
#      context: .
#      dockerfile: Dockerfile
#      target: dev
#
#    image: {{ cookiecutter.dockerhub_repo }}-dev:${TAG:-latest}
#
    user: root
    environment:
      GRANT_SUDO: 'yes'
#
#    volumes:
#      - ..:/workspaces/Fall2022-Private

    # command: 
    #   - jupyter
    #   - server 
    #   - --NotebookApp.ip='127.0.0.1'
    #   - --ServerApp.disable_check_xsrf=True
    #   - --NotebookApp.token=''
    #   - --NotebookApp.password=''